--GROUP BY 구문 : 집계 함수를 사용하여 값을 표시
--ROLLUP, CUBE, GROUPINGSET 등 집계 함수 사용 방법

SELECT DEPTNO, FLOOR(AVG(SAL)) AS AVG_SAL
	FROM EMP
	GROUP BY DEPTNO 
	;
	
SELECT DEPTNO
	  ,JOB
	  ,AVG(SAL)
	  FROM EMP
	  GROUP BY DEPTNO, JOB
	  ;
	 
SELECT	ENAME, DEPTNO, AVG(SAL)
	FROM EMP
	GROUP BY DEPTNO; -- 불가능
	
	
SELECT DEPTNO, JOB, AVG(SAL)
	FROM EMP
	GROUP BY DEPTNO, JOB 
	HAVING AVG(SAL) >= 2000
	ORDER BY DEPTNO, JOB
;
	  
SELECT DEPTNO, ENAME
 FROM EMP
 GROUP BY DEPTNO, ENAME 
 ;

SELECT DEPTNO
	 , LISTAGG(ENAME, ',')
	   WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES
 FROM EMP
 GROUP BY DEPTNO
 ;


SELECT DEPTNO, JOB, MAX(SAL)
 FROM EMP
 GROUP BY DEPTNO, JOB
 ORDER BY DEPTNO, JOB
 ;

SELECT *
	FROM (SELECT DEPTNO, JOB, SAL
		  FROM EMP)
PIVOT(MAX(SAL) FOR DEPTNO IN (10,20,30))
ORDER BY JOB;

SELECT DEPTNO
	 , MAX(DECODE(JOB,'CLERK',SAL)) AS "CLERK"
	 , MAX(DECODE(JOB,'SALESMAN',SAL)) AS "SALESMAN"
	 , MAX(DECODE(JOB,'PRESIDENT',SAL)) AS "PRESIDENT"	 
	 , MAX(DECODE(JOB,'MANAGER',SAL)) AS "MANAGER"
	 , MAX(DECODE(JOB,'ANALYST',SAL)) AS "ANALYST"
FROM EMP
GROUP BY DEPTNO 
ORDER BY DEPTNO
;
	 
	 
SELECT DEPTNO
	  ,JOB
	  ,COUNT(*)
	  ,MAX(SAL)
	  ,SUM(SAL)
	  ,AVG(SAL)
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB)
;
	 
SELECT DEPTNO
	  ,JOB
	  ,COUNT(*)
	  ,MAX(SAL)
	  ,SUM(SAL)
	  ,AVG(SAL)
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
;
	 
SELECT DEPTNO
	  ,JOB
	  ,COUNT(*)
	  ,MAX(SAL)
	  ,SUM(SAL)
	  ,AVG(SAL)
FROM EMP
GROUP BY GROUPING SETS(DEPTNO, JOB)
HAVING GROUPING(DEPTNO) = 1
;
	 
	 
	 
	 